// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailVerificationToken = `-- name: ConsumeEmailVerificationToken :exec
UPDATE email_verification_tokens
SET used_at = now()
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) ConsumeEmailVerificationToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, consumeEmailVerificationToken, id)
	return err
}

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :exec
UPDATE password_reset_tokens
SET used_at = now()
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, consumePasswordResetToken, id)
	return err
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO user_credentials (tenant_id, user_id, password_hash)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, user_id, password_hash, created_at, updated_at
`

type CreateCredentialParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	UserID       pgtype.UUID `json:"user_id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (UserCredential, error) {
	row := q.db.QueryRow(ctx, createCredential, arg.TenantID, arg.UserID, arg.PasswordHash)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (tenant_id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, token_hash, expires_at, used_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (tenant_id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO auth_sessions (
    tenant_id, user_id, family_id, refresh_token_hash,
    expires_at, ip_address, user_agent
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
RETURNING id, tenant_id, user_id, family_id, refresh_token_hash, expires_at, revoked_at, created_at, updated_at, last_used_at, ip_address, user_agent
`

type CreateSessionParams struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	FamilyID         pgtype.UUID        `json:"family_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	IpAddress        pgtype.Text        `json:"ip_address"`
	UserAgent        pgtype.Text        `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TenantID,
		arg.UserID,
		arg.FamilyID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM auth_sessions
WHERE (expires_at < $1 AND revoked_at IS NOT NULL)
   OR (expires_at < $1 AND expires_at < now())
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, before pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions, before)
	return err
}

const getActiveSessionByFamilyID = `-- name: GetActiveSessionByFamilyID :one
SELECT id, tenant_id, user_id, family_id, refresh_token_hash, expires_at, revoked_at, created_at, updated_at, last_used_at, ip_address, user_agent FROM auth_sessions
WHERE family_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
FOR UPDATE
`

func (q *Queries) GetActiveSessionByFamilyID(ctx context.Context, familyID pgtype.UUID) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByFamilyID, familyID)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const getCredentialByUserID = `-- name: GetCredentialByUserID :one
SELECT id, tenant_id, user_id, password_hash, created_at, updated_at FROM user_credentials
WHERE tenant_id = $1 AND user_id = $2
`

type GetCredentialByUserIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetCredentialByUserID(ctx context.Context, arg GetCredentialByUserIDParams) (UserCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByUserID, arg.TenantID, arg.UserID)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailVerificationTokenByHash = `-- name: GetEmailVerificationTokenByHash :one
SELECT id, tenant_id, user_id, token_hash, expires_at, used_at, created_at FROM email_verification_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByHash, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, tenant_id, user_id, token_hash, expires_at, used_at, created_at FROM password_reset_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, tenant_id, user_id, family_id, refresh_token_hash, expires_at, revoked_at, created_at, updated_at, last_used_at, ip_address, user_agent FROM auth_sessions
WHERE id = $1 AND tenant_id = $2
`

type GetSessionByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, arg.ID, arg.TenantID)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const invalidateEmailVerificationTokensForUser = `-- name: InvalidateEmailVerificationTokensForUser :exec
UPDATE email_verification_tokens
SET used_at = now()
WHERE tenant_id = $1 AND user_id = $2 AND used_at IS NULL
`

type InvalidateEmailVerificationTokensForUserParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) InvalidateEmailVerificationTokensForUser(ctx context.Context, arg InvalidateEmailVerificationTokensForUserParams) error {
	_, err := q.db.Exec(ctx, invalidateEmailVerificationTokensForUser, arg.TenantID, arg.UserID)
	return err
}

const invalidatePasswordResetTokensForUser = `-- name: InvalidatePasswordResetTokensForUser :exec
UPDATE password_reset_tokens
SET used_at = now()
WHERE tenant_id = $1 AND user_id = $2 AND used_at IS NULL
`

type InvalidatePasswordResetTokensForUserParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) InvalidatePasswordResetTokensForUser(ctx context.Context, arg InvalidatePasswordResetTokensForUserParams) error {
	_, err := q.db.Exec(ctx, invalidatePasswordResetTokensForUser, arg.TenantID, arg.UserID)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE auth_sessions
SET revoked_at = now(),
    updated_at = now()
WHERE tenant_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAllUserSessionsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, arg.TenantID, arg.UserID)
	return err
}

const revokeOtherUserSessions = `-- name: RevokeOtherUserSessions :exec
UPDATE auth_sessions
SET revoked_at = now(),
    updated_at = now()
WHERE tenant_id = $1
  AND user_id = $2
  AND id != $3
  AND revoked_at IS NULL
`

type RevokeOtherUserSessionsParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	UserID    pgtype.UUID `json:"user_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherUserSessions, arg.TenantID, arg.UserID, arg.SessionID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth_sessions
SET revoked_at = now(),
    updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.TenantID)
	return err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
UPDATE auth_sessions
SET refresh_token_hash = $1,
    last_used_at = now(),
    updated_at = now()
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, user_id, family_id, refresh_token_hash, expires_at, revoked_at, created_at, updated_at, last_used_at, ip_address, user_agent
`

type RotateRefreshTokenParams struct {
	RefreshTokenHash string      `json:"refresh_token_hash"`
	ID               pgtype.UUID `json:"id"`
	TenantID         pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken, arg.RefreshTokenHash, arg.ID, arg.TenantID)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :one
UPDATE user_credentials
SET password_hash = $1,
    updated_at = now()
WHERE tenant_id = $2 AND user_id = $3
RETURNING id, tenant_id, user_id, password_hash, created_at, updated_at
`

type UpdatePasswordHashParams struct {
	PasswordHash string      `json:"password_hash"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) (UserCredential, error) {
	row := q.db.QueryRow(ctx, updatePasswordHash, arg.PasswordHash, arg.TenantID, arg.UserID)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
