// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Status    string             `json:"status"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Email           string             `json:"email"`
	DisplayName     string             `json:"display_name"`
	Status          string             `json:"status"`
	EmailVerified   bool               `json:"email_verified"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	Metadata        []byte             `json:"metadata"`
	DeactivatedAt   pgtype.Timestamptz `json:"deactivated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
