// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcdb

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	HealthCheck(ctx context.Context) (int32, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SetEmailVerified(ctx context.Context, arg SetEmailVerifiedParams) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
