// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2)
`

type CountUsersParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.TenantID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, display_name, status, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, email, display_name, status, email_verified, email_verified_at, metadata, deactivated_at, created_at, updated_at
`

type CreateUserParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
	Status      string      `json:"status"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.DisplayName,
		arg.Status,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.Metadata,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, display_name, status, email_verified, email_verified_at, metadata, deactivated_at, created_at, updated_at FROM users
WHERE tenant_id = $1 AND lower(email) = lower($2)
`

type GetUserByEmailParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.Metadata,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, display_name, status, email_verified, email_verified_at, metadata, deactivated_at, created_at, updated_at FROM users
WHERE id = $1 AND tenant_id = $2
`

type GetUserByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.Metadata,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, email, display_name, status, email_verified, email_verified_at, metadata, deactivated_at, created_at, updated_at FROM users
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListUsersParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Status     pgtype.Text `json:"status"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.TenantID,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.EmailVerified,
			&i.EmailVerifiedAt,
			&i.Metadata,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmailVerified = `-- name: SetEmailVerified :one
UPDATE users
SET email_verified = true,
    email_verified_at = now(),
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, email, display_name, status, email_verified, email_verified_at, metadata, deactivated_at, created_at, updated_at
`

type SetEmailVerifiedParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) SetEmailVerified(ctx context.Context, arg SetEmailVerifiedParams) (User, error) {
	row := q.db.QueryRow(ctx, setEmailVerified, arg.ID, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.Metadata,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $1,
    display_name = $2,
    metadata = $3,
    email_verified = $4,
    email_verified_at = $5,
    updated_at = now()
WHERE id = $6 AND tenant_id = $7
RETURNING id, tenant_id, email, display_name, status, email_verified, email_verified_at, metadata, deactivated_at, created_at, updated_at
`

type UpdateUserParams struct {
	Email           string             `json:"email"`
	DisplayName     string             `json:"display_name"`
	Metadata        []byte             `json:"metadata"`
	EmailVerified   bool               `json:"email_verified"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.DisplayName,
		arg.Metadata,
		arg.EmailVerified,
		arg.EmailVerifiedAt,
		arg.ID,
		arg.TenantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.Metadata,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $1,
    deactivated_at = $2,
    updated_at = now()
WHERE id = $3 AND tenant_id = $4
RETURNING id, tenant_id, email, display_name, status, email_verified, email_verified_at, metadata, deactivated_at, created_at, updated_at
`

type UpdateUserStatusParams struct {
	Status        string             `json:"status"`
	DeactivatedAt pgtype.Timestamptz `json:"deactivated_at"`
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus,
		arg.Status,
		arg.DeactivatedAt,
		arg.ID,
		arg.TenantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.Metadata,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
